<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\AspireExperiment.ServiceDefaults\AspireExperiment.ServiceDefaults.csproj" />
    <ProjectReference Include="..\AspireExperiment.Web2.Client\AspireExperiment.Web2.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="8.0.12" />
  </ItemGroup>

</Project>
